# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Raspisaniye' do

pod 'Alamofire', '~> 3.2'
pod 'SwiftyJSON', '~> 2.3'
pod "SwiftDate"
pod "SwiftSpinner"
pod 'Google/CloudMessaging'
end

